FROM --platform=linux/amd64 node:17

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Install app dependencies
RUN yarn install

# prisma global
RUN npm i -g prisma

EXPOSE 3344

CMD [ "yarn", "dev" ]
